# Generated by Django 3.0.7 on 2020-06-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date_added',
            new_name='Date_Added',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='videodesc',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='videotitle',
            new_name='PostName',
        ),
    ]
