# Generated by Django 3.0.7 on 2020-06-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200620_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Post',
        ),
    ]
